// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: business.sql

package sqlc

import (
	"context"
)

const createBusiness = `-- name: CreateBusiness :one
INSERT INTO businesses (
  name, slug, timezone
) VALUES ( $1, $2, $3 )
RETURNING id, name, slug, timezone, created_at
`

type CreateBusinessParams struct {
	Name     string
	Slug     string
	Timezone string
}

func (q *Queries) CreateBusiness(ctx context.Context, arg CreateBusinessParams) (Business, error) {
	row := q.db.QueryRow(ctx, createBusiness, arg.Name, arg.Slug, arg.Timezone)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Timezone,
		&i.CreatedAt,
	)
	return i, err
}

const getBusinessBySlug = `-- name: GetBusinessBySlug :one
SELECT id, name, slug, timezone, created_at
  FROM businesses
  WHERE slug=$1
`

func (q *Queries) GetBusinessBySlug(ctx context.Context, slug string) (Business, error) {
	row := q.db.QueryRow(ctx, getBusinessBySlug, slug)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Timezone,
		&i.CreatedAt,
	)
	return i, err
}

const getBusinesses = `-- name: GetBusinesses :many
SELECT id, name, slug, timezone, created_at FROM businesses
`

func (q *Queries) GetBusinesses(ctx context.Context) ([]Business, error) {
	rows, err := q.db.Query(ctx, getBusinesses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Business
	for rows.Next() {
		var i Business
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Timezone,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
