// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Business struct {
	ID        pgtype.UUID
	Name      string
	Slug      string
	Timezone  string
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Name         string
	Email        string
	PasswordHash string
	Role         interface{}
	BusinessID   pgtype.UUID
	CreatedAt    pgtype.Timestamptz
}
